### ISSUE TITLE
Validations dont't work in production

### ISSUE THREAD

**Issue by jcottobboni** [twinge/enforce_schema_rules#3]
Validations are not working in production. Any idea why ? or already experienced it ?

**Comment by twinge** [comment]
I haven't used this plugin myself in quite some time. You can see from the commit logs that another dev contributed some patches to it a couple years ago. If you're interested in figuring out what needs to be done to get this to work in rails4 and open a PR, i'd be more than happy to review it and merge.

**Comment by eric1234** [comment]
I think it is something with your app as I am using the gem in a Rails 4 app without a problem even in production.
